name: Compliance (main)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      instance_id:
        description: "EC2 InstanceId (optional, else autodetect first SSM Online)"
        required: false

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  BUCKET:     ${{ vars.BUCKET }}
  ROLE_ARN:   ${{ vars.AWS_ROLE_ARN }}
  PHASE:      ci
# (… keep the rest of your existing jobs: section exactly as-is …)
